# Generated by Django 5.1 on 2024-08-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=150)),
                ('task', models.CharField(max_length=150)),
                ('descr', models.CharField(max_length=1000)),
                ('department', models.CharField(default='Общая', max_length=150)),
                ('deadline', models.CharField(max_length=150)),
            ],
        ),
    ]
