# Generated by Django 5.1 on 2024-08-17 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('surname', models.CharField(max_length=150)),
                ('fathername', models.CharField(max_length=150)),
                ('birthdate', models.CharField(max_length=150)),
                ('role', models.CharField(default='Работяга1', max_length=150)),
                ('login', models.CharField(max_length=150, unique=True)),
                ('nickname', models.CharField(default='', max_length=150, unique=True)),
                ('pension', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='users_info.user_info')),
            ],
        ),
    ]
